version: "3"
services:
  api:
    build: .
    image: spa_react_typescript_hello-world_basic_authentication
    container_name: spa_react_typescript_hello-world_basic_authentication
    ports:
      - 4040:4040
